name: Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: elisa-normal
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: elisa-actions/setup-go-and-mage@v1

      - name: Ensure go.mod and go.sum are up to date
        run: mage go:tidyAndVerify

      - name: Lint
        run: mage go:lint

      - name: Check vulnerabilities
        continue-on-error: true
        run: mage go:vulnCheck

      - name: Run license check
        run: mage go:licenses

      - name: Build binary
        run: mage go:build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        env:
          DOCKER_IMAGE_TAGS: sha-${{ github.event.pull_request.head.sha }}
        run: mage docker:build

      - name: Notify failure
        if: failure()
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          MATTERMOST_TEXT: "${{ github.repository }} PR build. Please check [here](${{ github.event.pull_request.html_url }}/checks)."
        run: |
          send-to-mattermost

  automerge:
    needs: [build]
    permissions:
      pull-requests: write
      contents: write
    runs-on: elisa-normal
    timeout-minutes: 15
    steps:
      - name: Automerge dependabot PR
        uses: elisa-actions/github-action-merge-dependabot@v3
        with:
          target: minor
          github-token: ${{ secrets.DOPS_SRE_PAT }}
